import { describe, it, expect } from 'vitest';
import {
  diagnose, maskUri, hostsFrom, nestedServerErrors, describeCredentials, splitUri,
} from '../../src/db/check.js';

const ctx = { srv: true, hosts: ['reclaimos.abc.mongodb.net'] };

describe('maskUri', () => {
  it('hides the password', () => {
    const masked = maskUri('mongodb+srv://myuser:s3cr3tPassw0rd@c.abc.mongodb.net/db');
    expect(masked).not.toContain('s3cr3tPassw0rd');
    expect(masked).toContain('myuser');
  });

  it('leaves a uri with no credentials alone', () => {
    const uri = 'mongodb://127.0.0.1:27017/reclaimos';
    expect(maskUri(uri)).toBe(uri);
  });

  it('masks the whole password even when it contains an unencoded @', () => {
    // Splitting on the first @ would print "••••••@ssw0rd" and leak most of it.
    const masked = maskUri('mongodb+srv://myuser:pa@ssw0rd@c.abc.mongodb.net/db');
    expect(masked).not.toContain('ssw0rd');
    expect(masked).toBe('mongodb+srv://myuser:••••••@c.abc.mongodb.net/db');
  });

  it('masks the whole password even when it contains an unencoded slash', () => {
    const masked = maskUri('mongodb+srv://myuser:pa/ss@c.abc.mongodb.net/db');
    expect(masked).not.toContain('pa/ss');
  });
});

describe('describeCredentials', () => {
  const of = (pwd) => describeCredentials(`mongodb+srv://myuser:${pwd}@c.abc.mongodb.net/db`);

  it('reports the length without revealing the password', () => {
    const d = of('cCsxoFeHZPRMArC6');
    expect(d.length).toBe(16);
    expect(JSON.stringify(d)).not.toContain('cCsxoFeHZPRMArC6');
  });

  it('recognises an autogenerated alphanumeric password as safe', () => {
    const d = of('aB3dEf7hJk9mNp2q');
    expect(d.alphanumeric).toBe(true);
    expect(d.needsEncoding).toEqual([]);
  });

  it('names the characters that need encoding', () => {
    const d = of('pa@ss-wo.rd');
    expect(d.alphanumeric).toBe(false);
    expect(d.needsEncoding).toContain('@');
  });

  it('locates the password correctly even with an unencoded @ in it', () => {
    const d = describeCredentials('mongodb+srv://myuser:pa@ssw0rd@c.abc.mongodb.net/db');
    expect(d.user).toBe('myuser');
    expect(d.length).toBe('pa@ssw0rd'.length);
    expect(d.ambiguous).toBe(false);
  });

  it('admits when a / in the password makes the string unparseable', () => {
    const d = describeCredentials('mongodb+srv://myuser:pa/ssw0rd@c.abc.mongodb.net/db');
    expect(d.ambiguous).toBe(true);
  });

  it('spots an empty password', () => {
    expect(of('').empty).toBe(true);
  });

  it('says so when the uri carries no credentials at all', () => {
    expect(describeCredentials('mongodb://127.0.0.1:27017/reclaimos')).toEqual({ present: false });
  });
});

describe('diagnose', () => {
  it('reports a rejected password as credentials, not as a network problem', () => {
    const err = Object.assign(new Error('bad auth : authentication failed'), {
      name: 'MongoServerError', code: 8000, codeName: 'AtlasError',
    });
    const { cause, fix } = diagnose(err, ctx);
    expect(cause).toMatch(/rejected the username or password/);
    expect(fix.join(' ')).toMatch(/rotated password/);
    expect(cause).not.toMatch(/allowlist|timeout/i);
  });

  it('reports a failed SRV lookup as DNS', () => {
    const err = Object.assign(new Error('querySrv ESERVFAIL'), { code: 'ESERVFAIL' });
    expect(diagnose(err, ctx).cause).toMatch(/SRV lookup/);
  });

  it('reports an unreachable replica set as the IP allowlist', () => {
    const err = Object.assign(new Error('Could not connect'), {
      name: 'MongooseServerSelectionError',
      reason: { type: 'ReplicaSetNoPrimary', servers: new Map() },
    });
    const { cause, fix } = diagnose(err, ctx);
    expect(cause).toContain('ReplicaSetNoPrimary');
    expect(fix.join(' ')).toMatch(/Network Access/);
  });

  it('digs an auth failure out of a selection error rather than blaming the IP', () => {
    // Reporting "check your IP" here would send someone down the wrong path.
    const err = Object.assign(new Error('Could not connect'), {
      name: 'MongooseServerSelectionError',
      reason: {
        type: 'ReplicaSetNoPrimary',
        servers: new Map([['a:27017', { error: new Error('bad auth : authentication failed') }]]),
      },
    });
    expect(diagnose(err, ctx).cause).toMatch(/rejected the username or password/);
  });

  it('matches the driver name as well as the mongoose one', () => {
    const err = Object.assign(new Error('timed out'), { name: 'MongoServerSelectionError' });
    expect(diagnose(err, ctx).cause).toMatch(/no server answered/);
  });

  it('falls back to the driver message rather than inventing a cause', () => {
    expect(diagnose(new Error('something entirely new'), ctx).cause).toBe('something entirely new');
  });
});

describe('hostsFrom and splitUri', () => {
  it('detects srv style', () => {
    expect(hostsFrom('mongodb+srv://u:p@c.abc.mongodb.net/db'))
      .toEqual({ srv: true, hosts: ['c.abc.mongodb.net'] });
  });

  it('lists every host in a standard string', () => {
    expect(hostsFrom('mongodb://u:p@a:27017,b:27017,c:27017/db').hosts).toHaveLength(3);
  });

  it('splits at the last @, not the first', () => {
    expect(splitUri('mongodb+srv://u:p@ss@host.net/db').userinfo).toBe('u:p@ss');
  });

  it('reports no credentials for a non-mongo scheme', () => {
    expect(splitUri('https://cloud.mongodb.com/v2/abc').present).toBe(false);
  });
});

describe('nestedServerErrors', () => {
  it('returns nothing when there is no reason attached', () => {
    expect(nestedServerErrors(new Error('plain'))).toEqual([]);
  });

  it('skips servers that reported no error', () => {
    const err = Object.assign(new Error('x'), {
      reason: { servers: new Map([['a', {}], ['b', { error: new Error('real') }]]) },
    });
    expect(nestedServerErrors(err)).toEqual(['real']);
  });
});
