/**
 * Generates src/styles/_palette.scss.
 *
 * The scales are defined in OKLCH and written out as hex. OKLCH because a step in
 * its lightness axis looks like the same step to the eye, which HSL does not give
 * you — drag an HSL brightness slider on a blue and it goes muddy and violet on
 * the way down. Hex on the way out because every browser reads it, and because the
 * contrast tests can then measure the exact values that ship.
 *
 * Run with: npm run palette
 *
 * Nothing imports this at build time. It is run by hand when a hue changes, and
 * its output is committed, so the stylesheet never depends on a script running.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// ── OKLCH → sRGB, after Björn Ottosson's reference implementation ────────────
const cube = (x) => x * x * x;

function oklabToLinearSrgb(L, a, b) {
  const l = cube(L + 0.3963377774 * a + 0.2158037573 * b);
  const m = cube(L - 0.1055613458 * a - 0.0638541728 * b);
  const s = cube(L - 0.0894841775 * a - 1.2914855480 * b);

  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s,
  ];
}

const gammaEncode = (c) => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055);
const inGamut = ([r, g, b]) => [r, g, b].every((c) => c >= -0.0001 && c <= 1.0001);

/**
 * A wide-gamut OKLCH value can name a colour sRGB cannot show. Rather than let the
 * channels clip — which shifts the hue — walk the chroma down until it fits. The
 * hue and lightness asked for are preserved; only the saturation gives way.
 */
function oklchToHex(L, C, hueDegrees) {
  const h = (hueDegrees * Math.PI) / 180;
  let chroma = C;

  for (let i = 0; i < 200; i += 1) {
    const linear = oklabToLinearSrgb(L, chroma * Math.cos(h), chroma * Math.sin(h));
    if (inGamut(linear)) {
      const hex = linear
        .map((c) => Math.round(Math.min(1, Math.max(0, gammaEncode(c))) * 255))
        .map((v) => v.toString(16).padStart(2, '0'))
        .join('');
      return `#${hex}`;
    }
    chroma -= C / 200;
  }
  return '#000000';
}

/**
 * One ladder of lightness for every scale, so a 600 in one hue weighs the same as
 * a 600 in another. That is the property that makes swapping a hue safe later.
 */
const STEPS = [
  [50, 0.985], [100, 0.965], [200, 0.925], [300, 0.870], [400, 0.780],
  [500, 0.680], [600, 0.590], [700, 0.500], [800, 0.410], [900, 0.320],
  [950, 0.235], [975, 0.175],
];

/** Chroma peaks in the middle and eases off at both ends, or the tints go muddy. */
const CHROMA_CURVE = [0.18, 0.30, 0.55, 0.80, 0.95, 1.0, 0.98, 0.88, 0.74, 0.58, 0.44, 0.36];

const SCALES = {
  // Warm near-black through warm paper. Not blue-grey: this is the surface the
  // whole product sits on, and a hint of warmth reads as paper rather than steel.
  ink: { hue: 75, chroma: 0.016, flat: true },

  // The one accent. Links, focus, the selected thing — and nothing else, so that
  // colour anywhere else in the interface is carrying information.
  accent: { hue: 250, chroma: 0.155 },

  // Reserved for meaning, never for decoration.
  success: { hue: 152, chroma: 0.135 },
  warning: { hue: 75, chroma: 0.145 },
  danger: { hue: 27, chroma: 0.165 },
};

function buildScale({ hue, chroma, flat }) {
  return STEPS.map(([step, lightness], i) => {
    // The neutral ramp keeps its tint nearly constant; a chroma curve on a near-grey
    // would make the mid greys visibly yellow.
    const c = flat ? chroma * (0.35 + 0.65 * CHROMA_CURVE[i]) : chroma * CHROMA_CURVE[i];
    return [step, oklchToHex(lightness, c, hue)];
  });
}

const lines = [
  '// GENERATED by scripts/palette.mjs — run `npm run palette` after editing that file.',
  '//',
  '// Raw colour, and nothing else. These are the only hex values in the project, and',
  '// no component may name one: components use the semantic tokens in _tokens.scss,',
  '// which is what lets the dark theme be a remapping rather than a second stylesheet.',
  '//',
  '// Every scale climbs the same lightness ladder, so a 600 in one hue carries the',
  '// same visual weight as a 600 in another. Changing a hue is then a one-line edit',
  '// in scripts/palette.mjs rather than a re-audit of every screen.',
  '',
];

for (const [name, spec] of Object.entries(SCALES)) {
  const scale = buildScale(spec);
  lines.push(`// ${name} — OKLCH hue ${spec.hue}, chroma ${spec.chroma}`);
  lines.push(`$${name}: (`);
  for (const [step, hex] of scale) lines.push(`  ${step}: ${hex},`);
  lines.push(');', '');
}

lines.push('// Absolutes, for the rare case that needs one regardless of theme.');
lines.push('$white: #ffffff;');
lines.push('$black: #000000;');
lines.push('');

const out = fileURLToPath(new URL('../src/styles/_palette.scss', import.meta.url));
writeFileSync(out, lines.join('\n'));

console.log(`wrote ${out}`);
for (const [name, spec] of Object.entries(SCALES)) {
  console.log(`  ${name.padEnd(8)} ${buildScale(spec).map(([, hex]) => hex).join(' ')}`);
}
